server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.cn.zhang.model
  mapper-locations: classpath:mybatis/mapper/**/*.xml


spring:
  application:
    name: product-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.102.150.239:3306/product?characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password: root123
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-total: 10
      max-wait-millis: 150

